import Index from "@/components/modules/Index";
import prisma from "@/lib/db/prisma.db";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Event connect - Find and join events with others",
  description: "Generated by create next app",
};

export default async function Home ()
{
  const users = await prisma.user.findMany();
  console.log(  users );

  return (
    <Index/>
  );
}