import Index from "@/components/modules/Index";
import { authOptions } from "@/lib/services/auth/auth.option";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Event connect - Find and join events with others",
  description: "Generated by create next app",
};

export default async function Home ()
{


  const session = await getServerSession( authOptions );
  // console.log(session)
  
  return (
    <Index role={ session?.user?.role} />
  );
}