import Index from "@/components/modules/Index";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Event connect - Find and join events with others",
  description: "Generated by create next app",
};

export default async function Home ()
{

  return (
    <Index/>
  );
}